// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pkg/agent/proto/switch_agent.proto

package switchagentproto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwitchAgentService_GetDeviceInfo_FullMethodName           = "/switchagent.v1.SwitchAgentService/GetDeviceInfo"
	SwitchAgentService_ListInterfaces_FullMethodName          = "/switchagent.v1.SwitchAgentService/ListInterfaces"
	SwitchAgentService_SetInterfaceAdminStatus_FullMethodName = "/switchagent.v1.SwitchAgentService/SetInterfaceAdminStatus"
	SwitchAgentService_SetInterfaceAliasName_FullMethodName   = "/switchagent.v1.SwitchAgentService/SetInterfaceAliasName"
	SwitchAgentService_GetInterface_FullMethodName            = "/switchagent.v1.SwitchAgentService/GetInterface"
	SwitchAgentService_GetInterfaceNeighbor_FullMethodName    = "/switchagent.v1.SwitchAgentService/GetInterfaceNeighbor"
	SwitchAgentService_ListPorts_FullMethodName               = "/switchagent.v1.SwitchAgentService/ListPorts"
	SwitchAgentService_SaveConfig_FullMethodName              = "/switchagent.v1.SwitchAgentService/SaveConfig"
	SwitchAgentService_Reboot_FullMethodName                  = "/switchagent.v1.SwitchAgentService/Reboot"
	SwitchAgentService_OnieBootModeInstall_FullMethodName     = "/switchagent.v1.SwitchAgentService/OnieBootModeInstall"
	SwitchAgentService_RestartSystemdService_FullMethodName   = "/switchagent.v1.SwitchAgentService/RestartSystemdService"
	SwitchAgentService_RebootCause_FullMethodName             = "/switchagent.v1.SwitchAgentService/RebootCause"
	SwitchAgentService_FactoryReset_FullMethodName            = "/switchagent.v1.SwitchAgentService/FactoryReset"
	SwitchAgentService_GetReadiness_FullMethodName            = "/switchagent.v1.SwitchAgentService/GetReadiness"
	SwitchAgentService_Reprovision_FullMethodName             = "/switchagent.v1.SwitchAgentService/Reprovision"
)

// SwitchAgentServiceClient is the client API for SwitchAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The interface service definition.
type SwitchAgentServiceClient interface {
	GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error)
	ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error)
	SetInterfaceAdminStatus(ctx context.Context, in *SetInterfaceAdminStatusRequest, opts ...grpc.CallOption) (*SetInterfaceAdminStatusResponse, error)
	SetInterfaceAliasName(ctx context.Context, in *SetInterfaceAliasNameRequest, opts ...grpc.CallOption) (*SetInterfaceAliasNameResponse, error)
	GetInterface(ctx context.Context, in *GetInterfaceRequest, opts ...grpc.CallOption) (*GetInterfaceResponse, error)
	GetInterfaceNeighbor(ctx context.Context, in *GetInterfaceNeighborRequest, opts ...grpc.CallOption) (*GetInterfaceNeighborResponse, error)
	ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error)
	// gNOI alternatives
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error)
	Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*RebootResponse, error)
	OnieBootModeInstall(ctx context.Context, in *OnieBootModeInstallRequest, opts ...grpc.CallOption) (*OnieBootModeInstallResponse, error)
	RestartSystemdService(ctx context.Context, in *RestartSystemdServiceRequest, opts ...grpc.CallOption) (*RestartSystemdServiceResponse, error)
	RebootCause(ctx context.Context, in *RebootCauseRequest, opts ...grpc.CallOption) (*RebootCauseResponse, error)
	FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*FactoryResetResponse, error)
	GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessResponse, error)
	Reprovision(ctx context.Context, in *ReprovisionRequest, opts ...grpc.CallOption) (*ReprovisionResponse, error)
}

type switchAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwitchAgentServiceClient(cc grpc.ClientConnInterface) SwitchAgentServiceClient {
	return &switchAgentServiceClient{cc}
}

func (c *switchAgentServiceClient) GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceInfoResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_ListInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) SetInterfaceAdminStatus(ctx context.Context, in *SetInterfaceAdminStatusRequest, opts ...grpc.CallOption) (*SetInterfaceAdminStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInterfaceAdminStatusResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_SetInterfaceAdminStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) SetInterfaceAliasName(ctx context.Context, in *SetInterfaceAliasNameRequest, opts ...grpc.CallOption) (*SetInterfaceAliasNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInterfaceAliasNameResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_SetInterfaceAliasName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) GetInterface(ctx context.Context, in *GetInterfaceRequest, opts ...grpc.CallOption) (*GetInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterfaceResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) GetInterfaceNeighbor(ctx context.Context, in *GetInterfaceNeighborRequest, opts ...grpc.CallOption) (*GetInterfaceNeighborResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterfaceNeighborResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetInterfaceNeighbor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPortsResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_ListPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConfigResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_SaveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*RebootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebootResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) OnieBootModeInstall(ctx context.Context, in *OnieBootModeInstallRequest, opts ...grpc.CallOption) (*OnieBootModeInstallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnieBootModeInstallResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_OnieBootModeInstall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) RestartSystemdService(ctx context.Context, in *RestartSystemdServiceRequest, opts ...grpc.CallOption) (*RestartSystemdServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartSystemdServiceResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_RestartSystemdService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) RebootCause(ctx context.Context, in *RebootCauseRequest, opts ...grpc.CallOption) (*RebootCauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebootCauseResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_RebootCause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*FactoryResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactoryResetResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_FactoryReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadinessResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetReadiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) Reprovision(ctx context.Context, in *ReprovisionRequest, opts ...grpc.CallOption) (*ReprovisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReprovisionResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_Reprovision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwitchAgentServiceServer is the server API for SwitchAgentService service.
// All implementations must embed UnimplementedSwitchAgentServiceServer
// for forward compatibility.
//
// The interface service definition.
type SwitchAgentServiceServer interface {
	GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error)
	ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error)
	SetInterfaceAdminStatus(context.Context, *SetInterfaceAdminStatusRequest) (*SetInterfaceAdminStatusResponse, error)
	SetInterfaceAliasName(context.Context, *SetInterfaceAliasNameRequest) (*SetInterfaceAliasNameResponse, error)
	GetInterface(context.Context, *GetInterfaceRequest) (*GetInterfaceResponse, error)
	GetInterfaceNeighbor(context.Context, *GetInterfaceNeighborRequest) (*GetInterfaceNeighborResponse, error)
	ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error)
	// gNOI alternatives
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error)
	Reboot(context.Context, *RebootRequest) (*RebootResponse, error)
	OnieBootModeInstall(context.Context, *OnieBootModeInstallRequest) (*OnieBootModeInstallResponse, error)
	RestartSystemdService(context.Context, *RestartSystemdServiceRequest) (*RestartSystemdServiceResponse, error)
	RebootCause(context.Context, *RebootCauseRequest) (*RebootCauseResponse, error)
	FactoryReset(context.Context, *FactoryResetRequest) (*FactoryResetResponse, error)
	GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessResponse, error)
	Reprovision(context.Context, *ReprovisionRequest) (*ReprovisionResponse, error)
	mustEmbedUnimplementedSwitchAgentServiceServer()
}

// UnimplementedSwitchAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwitchAgentServiceServer struct{}

func (UnimplementedSwitchAgentServiceServer) GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedSwitchAgentServiceServer) ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedSwitchAgentServiceServer) SetInterfaceAdminStatus(context.Context, *SetInterfaceAdminStatusRequest) (*SetInterfaceAdminStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInterfaceAdminStatus not implemented")
}
func (UnimplementedSwitchAgentServiceServer) SetInterfaceAliasName(context.Context, *SetInterfaceAliasNameRequest) (*SetInterfaceAliasNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInterfaceAliasName not implemented")
}
func (UnimplementedSwitchAgentServiceServer) GetInterface(context.Context, *GetInterfaceRequest) (*GetInterfaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterface not implemented")
}
func (UnimplementedSwitchAgentServiceServer) GetInterfaceNeighbor(context.Context, *GetInterfaceNeighborRequest) (*GetInterfaceNeighborResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterfaceNeighbor not implemented")
}
func (UnimplementedSwitchAgentServiceServer) ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPorts not implemented")
}
func (UnimplementedSwitchAgentServiceServer) SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveConfig not implemented")
}
func (UnimplementedSwitchAgentServiceServer) Reboot(context.Context, *RebootRequest) (*RebootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedSwitchAgentServiceServer) OnieBootModeInstall(context.Context, *OnieBootModeInstallRequest) (*OnieBootModeInstallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnieBootModeInstall not implemented")
}
func (UnimplementedSwitchAgentServiceServer) RestartSystemdService(context.Context, *RestartSystemdServiceRequest) (*RestartSystemdServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartSystemdService not implemented")
}
func (UnimplementedSwitchAgentServiceServer) RebootCause(context.Context, *RebootCauseRequest) (*RebootCauseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebootCause not implemented")
}
func (UnimplementedSwitchAgentServiceServer) FactoryReset(context.Context, *FactoryResetRequest) (*FactoryResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactoryReset not implemented")
}
func (UnimplementedSwitchAgentServiceServer) GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadiness not implemented")
}
func (UnimplementedSwitchAgentServiceServer) Reprovision(context.Context, *ReprovisionRequest) (*ReprovisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reprovision not implemented")
}
func (UnimplementedSwitchAgentServiceServer) mustEmbedUnimplementedSwitchAgentServiceServer() {}
func (UnimplementedSwitchAgentServiceServer) testEmbeddedByValue()                            {}

// UnsafeSwitchAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwitchAgentServiceServer will
// result in compilation errors.
type UnsafeSwitchAgentServiceServer interface {
	mustEmbedUnimplementedSwitchAgentServiceServer()
}

func RegisterSwitchAgentServiceServer(s grpc.ServiceRegistrar, srv SwitchAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedSwitchAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwitchAgentService_ServiceDesc, srv)
}

func _SwitchAgentService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetDeviceInfo(ctx, req.(*GetDeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_ListInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).ListInterfaces(ctx, req.(*ListInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_SetInterfaceAdminStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInterfaceAdminStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).SetInterfaceAdminStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_SetInterfaceAdminStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).SetInterfaceAdminStatus(ctx, req.(*SetInterfaceAdminStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_SetInterfaceAliasName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInterfaceAliasNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).SetInterfaceAliasName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_SetInterfaceAliasName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).SetInterfaceAliasName(ctx, req.(*SetInterfaceAliasNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_GetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetInterface(ctx, req.(*GetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_GetInterfaceNeighbor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfaceNeighborRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetInterfaceNeighbor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetInterfaceNeighbor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetInterfaceNeighbor(ctx, req.(*GetInterfaceNeighborRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_ListPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).ListPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_ListPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).ListPorts(ctx, req.(*ListPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_SaveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).Reboot(ctx, req.(*RebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_OnieBootModeInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnieBootModeInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).OnieBootModeInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_OnieBootModeInstall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).OnieBootModeInstall(ctx, req.(*OnieBootModeInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_RestartSystemdService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartSystemdServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).RestartSystemdService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_RestartSystemdService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).RestartSystemdService(ctx, req.(*RestartSystemdServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_RebootCause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootCauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).RebootCause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_RebootCause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).RebootCause(ctx, req.(*RebootCauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_FactoryReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).FactoryReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_FactoryReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).FactoryReset(ctx, req.(*FactoryResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_GetReadiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetReadiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetReadiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetReadiness(ctx, req.(*GetReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_Reprovision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReprovisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).Reprovision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_Reprovision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).Reprovision(ctx, req.(*ReprovisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwitchAgentService_ServiceDesc is the grpc.ServiceDesc for SwitchAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwitchAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.SwitchAgentService",
	HandlerType: (*SwitchAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceInfo",
			Handler:    _SwitchAgentService_GetDeviceInfo_Handler,
		},
		{
			MethodName: "ListInterfaces",
			Handler:    _SwitchAgentService_ListInterfaces_Handler,
		},
		{
			MethodName: "SetInterfaceAdminStatus",
			Handler:    _SwitchAgentService_SetInterfaceAdminStatus_Handler,
		},
		{
			MethodName: "SetInterfaceAliasName",
			Handler:    _SwitchAgentService_SetInterfaceAliasName_Handler,
		},
		{
			MethodName: "GetInterface",
			Handler:    _SwitchAgentService_GetInterface_Handler,
		},
		{
			MethodName: "GetInterfaceNeighbor",
			Handler:    _SwitchAgentService_GetInterfaceNeighbor_Handler,
		},
		{
			MethodName: "ListPorts",
			Handler:    _SwitchAgentService_ListPorts_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _SwitchAgentService_SaveConfig_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _SwitchAgentService_Reboot_Handler,
		},
		{
			MethodName: "OnieBootModeInstall",
			Handler:    _SwitchAgentService_OnieBootModeInstall_Handler,
		},
		{
			MethodName: "RestartSystemdService",
			Handler:    _SwitchAgentService_RestartSystemdService_Handler,
		},
		{
			MethodName: "RebootCause",
			Handler:    _SwitchAgentService_RebootCause_Handler,
		},
		{
			MethodName: "FactoryReset",
			Handler:    _SwitchAgentService_FactoryReset_Handler,
		},
		{
			MethodName: "GetReadiness",
			Handler:    _SwitchAgentService_GetReadiness_Handler,
		},
		{
			MethodName: "Reprovision",
			Handler:    _SwitchAgentService_Reprovision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/proto/switch_agent.proto",
}

const (
	FabricSonicService_GetDevice_FullMethodName              = "/switchagent.v1.FabricSonicService/GetDevice"
	FabricSonicService_ApplySwitch_FullMethodName            = "/switchagent.v1.FabricSonicService/ApplySwitch"
	FabricSonicService_DeleteSwitch_FullMethodName           = "/switchagent.v1.FabricSonicService/DeleteSwitch"
	FabricSonicService_GetCellStatus_FullMethodName          = "/switchagent.v1.FabricSonicService/GetCellStatus"
	FabricSonicService_GetInterface_FullMethodName           = "/switchagent.v1.FabricSonicService/GetInterface"
	FabricSonicService_GetInterfaceState_FullMethodName      = "/switchagent.v1.FabricSonicService/GetInterfaceState"
	FabricSonicService_SetInterfaceAdminState_FullMethodName = "/switchagent.v1.FabricSonicService/SetInterfaceAdminState"
	FabricSonicService_ListInterfacesV2_FullMethodName       = "/switchagent.v1.FabricSonicService/ListInterfacesV2"
)

// FabricSonicServiceClient is the client API for FabricSonicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FabricSonicService manages SONiC switch configuration and interface state via gRPC.
type FabricSonicServiceClient interface {
	// Switch configuration and interface management
	GetDevice(ctx context.Context, in *FabricGetDeviceRequest, opts ...grpc.CallOption) (*FabricGetDeviceResponse, error)
	ApplySwitch(ctx context.Context, in *ApplySwitchRequest, opts ...grpc.CallOption) (*ApplySwitchResponse, error)
	DeleteSwitch(ctx context.Context, in *DeleteSwitchRequest, opts ...grpc.CallOption) (*DeleteSwitchResponse, error)
	GetCellStatus(ctx context.Context, in *GetCellStatusRequest, opts ...grpc.CallOption) (*GetCellStatusResponse, error)
	GetInterface(ctx context.Context, in *FabricGetInterfaceRequest, opts ...grpc.CallOption) (*FabricGetInterfaceResponse, error)
	GetInterfaceState(ctx context.Context, in *FabricGetInterfaceStateRequest, opts ...grpc.CallOption) (*FabricGetInterfaceStateResponse, error)
	SetInterfaceAdminState(ctx context.Context, in *FabricSetInterfaceAdminStateRequest, opts ...grpc.CallOption) (*FabricSetInterfaceAdminStateResponse, error)
	ListInterfacesV2(ctx context.Context, in *ListInterfacesRequestV2, opts ...grpc.CallOption) (*ListInterfacesResponseV2, error)
}

type fabricSonicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFabricSonicServiceClient(cc grpc.ClientConnInterface) FabricSonicServiceClient {
	return &fabricSonicServiceClient{cc}
}

func (c *fabricSonicServiceClient) GetDevice(ctx context.Context, in *FabricGetDeviceRequest, opts ...grpc.CallOption) (*FabricGetDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FabricGetDeviceResponse)
	err := c.cc.Invoke(ctx, FabricSonicService_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricSonicServiceClient) ApplySwitch(ctx context.Context, in *ApplySwitchRequest, opts ...grpc.CallOption) (*ApplySwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySwitchResponse)
	err := c.cc.Invoke(ctx, FabricSonicService_ApplySwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricSonicServiceClient) DeleteSwitch(ctx context.Context, in *DeleteSwitchRequest, opts ...grpc.CallOption) (*DeleteSwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSwitchResponse)
	err := c.cc.Invoke(ctx, FabricSonicService_DeleteSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricSonicServiceClient) GetCellStatus(ctx context.Context, in *GetCellStatusRequest, opts ...grpc.CallOption) (*GetCellStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCellStatusResponse)
	err := c.cc.Invoke(ctx, FabricSonicService_GetCellStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricSonicServiceClient) GetInterface(ctx context.Context, in *FabricGetInterfaceRequest, opts ...grpc.CallOption) (*FabricGetInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FabricGetInterfaceResponse)
	err := c.cc.Invoke(ctx, FabricSonicService_GetInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricSonicServiceClient) GetInterfaceState(ctx context.Context, in *FabricGetInterfaceStateRequest, opts ...grpc.CallOption) (*FabricGetInterfaceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FabricGetInterfaceStateResponse)
	err := c.cc.Invoke(ctx, FabricSonicService_GetInterfaceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricSonicServiceClient) SetInterfaceAdminState(ctx context.Context, in *FabricSetInterfaceAdminStateRequest, opts ...grpc.CallOption) (*FabricSetInterfaceAdminStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FabricSetInterfaceAdminStateResponse)
	err := c.cc.Invoke(ctx, FabricSonicService_SetInterfaceAdminState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricSonicServiceClient) ListInterfacesV2(ctx context.Context, in *ListInterfacesRequestV2, opts ...grpc.CallOption) (*ListInterfacesResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponseV2)
	err := c.cc.Invoke(ctx, FabricSonicService_ListInterfacesV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FabricSonicServiceServer is the server API for FabricSonicService service.
// All implementations must embed UnimplementedFabricSonicServiceServer
// for forward compatibility.
//
// FabricSonicService manages SONiC switch configuration and interface state via gRPC.
type FabricSonicServiceServer interface {
	// Switch configuration and interface management
	GetDevice(context.Context, *FabricGetDeviceRequest) (*FabricGetDeviceResponse, error)
	ApplySwitch(context.Context, *ApplySwitchRequest) (*ApplySwitchResponse, error)
	DeleteSwitch(context.Context, *DeleteSwitchRequest) (*DeleteSwitchResponse, error)
	GetCellStatus(context.Context, *GetCellStatusRequest) (*GetCellStatusResponse, error)
	GetInterface(context.Context, *FabricGetInterfaceRequest) (*FabricGetInterfaceResponse, error)
	GetInterfaceState(context.Context, *FabricGetInterfaceStateRequest) (*FabricGetInterfaceStateResponse, error)
	SetInterfaceAdminState(context.Context, *FabricSetInterfaceAdminStateRequest) (*FabricSetInterfaceAdminStateResponse, error)
	ListInterfacesV2(context.Context, *ListInterfacesRequestV2) (*ListInterfacesResponseV2, error)
	mustEmbedUnimplementedFabricSonicServiceServer()
}

// UnimplementedFabricSonicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFabricSonicServiceServer struct{}

func (UnimplementedFabricSonicServiceServer) GetDevice(context.Context, *FabricGetDeviceRequest) (*FabricGetDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedFabricSonicServiceServer) ApplySwitch(context.Context, *ApplySwitchRequest) (*ApplySwitchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplySwitch not implemented")
}
func (UnimplementedFabricSonicServiceServer) DeleteSwitch(context.Context, *DeleteSwitchRequest) (*DeleteSwitchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSwitch not implemented")
}
func (UnimplementedFabricSonicServiceServer) GetCellStatus(context.Context, *GetCellStatusRequest) (*GetCellStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCellStatus not implemented")
}
func (UnimplementedFabricSonicServiceServer) GetInterface(context.Context, *FabricGetInterfaceRequest) (*FabricGetInterfaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterface not implemented")
}
func (UnimplementedFabricSonicServiceServer) GetInterfaceState(context.Context, *FabricGetInterfaceStateRequest) (*FabricGetInterfaceStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterfaceState not implemented")
}
func (UnimplementedFabricSonicServiceServer) SetInterfaceAdminState(context.Context, *FabricSetInterfaceAdminStateRequest) (*FabricSetInterfaceAdminStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInterfaceAdminState not implemented")
}
func (UnimplementedFabricSonicServiceServer) ListInterfacesV2(context.Context, *ListInterfacesRequestV2) (*ListInterfacesResponseV2, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterfacesV2 not implemented")
}
func (UnimplementedFabricSonicServiceServer) mustEmbedUnimplementedFabricSonicServiceServer() {}
func (UnimplementedFabricSonicServiceServer) testEmbeddedByValue()                            {}

// UnsafeFabricSonicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FabricSonicServiceServer will
// result in compilation errors.
type UnsafeFabricSonicServiceServer interface {
	mustEmbedUnimplementedFabricSonicServiceServer()
}

func RegisterFabricSonicServiceServer(s grpc.ServiceRegistrar, srv FabricSonicServiceServer) {
	// If the following call panics, it indicates UnimplementedFabricSonicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FabricSonicService_ServiceDesc, srv)
}

func _FabricSonicService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FabricGetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricSonicServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricSonicService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricSonicServiceServer).GetDevice(ctx, req.(*FabricGetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricSonicService_ApplySwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricSonicServiceServer).ApplySwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricSonicService_ApplySwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricSonicServiceServer).ApplySwitch(ctx, req.(*ApplySwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricSonicService_DeleteSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricSonicServiceServer).DeleteSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricSonicService_DeleteSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricSonicServiceServer).DeleteSwitch(ctx, req.(*DeleteSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricSonicService_GetCellStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricSonicServiceServer).GetCellStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricSonicService_GetCellStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricSonicServiceServer).GetCellStatus(ctx, req.(*GetCellStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricSonicService_GetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FabricGetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricSonicServiceServer).GetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricSonicService_GetInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricSonicServiceServer).GetInterface(ctx, req.(*FabricGetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricSonicService_GetInterfaceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FabricGetInterfaceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricSonicServiceServer).GetInterfaceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricSonicService_GetInterfaceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricSonicServiceServer).GetInterfaceState(ctx, req.(*FabricGetInterfaceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricSonicService_SetInterfaceAdminState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FabricSetInterfaceAdminStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricSonicServiceServer).SetInterfaceAdminState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricSonicService_SetInterfaceAdminState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricSonicServiceServer).SetInterfaceAdminState(ctx, req.(*FabricSetInterfaceAdminStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricSonicService_ListInterfacesV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequestV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricSonicServiceServer).ListInterfacesV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricSonicService_ListInterfacesV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricSonicServiceServer).ListInterfacesV2(ctx, req.(*ListInterfacesRequestV2))
	}
	return interceptor(ctx, in, info, handler)
}

// FabricSonicService_ServiceDesc is the grpc.ServiceDesc for FabricSonicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FabricSonicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.FabricSonicService",
	HandlerType: (*FabricSonicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevice",
			Handler:    _FabricSonicService_GetDevice_Handler,
		},
		{
			MethodName: "ApplySwitch",
			Handler:    _FabricSonicService_ApplySwitch_Handler,
		},
		{
			MethodName: "DeleteSwitch",
			Handler:    _FabricSonicService_DeleteSwitch_Handler,
		},
		{
			MethodName: "GetCellStatus",
			Handler:    _FabricSonicService_GetCellStatus_Handler,
		},
		{
			MethodName: "GetInterface",
			Handler:    _FabricSonicService_GetInterface_Handler,
		},
		{
			MethodName: "GetInterfaceState",
			Handler:    _FabricSonicService_GetInterfaceState_Handler,
		},
		{
			MethodName: "SetInterfaceAdminState",
			Handler:    _FabricSonicService_SetInterfaceAdminState_Handler,
		},
		{
			MethodName: "ListInterfacesV2",
			Handler:    _FabricSonicService_ListInterfacesV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/proto/switch_agent.proto",
}
