#!/bin/bash
set -euo pipefail

# Generated by sonic-operator 'switch-1'

# Configure ONIE install discovery for the next and every subsequent SONiC reboot.
mkdir -p /onieboot
cat >/etc/systemd/system/onieboot.mount <<'EOF'
[Unit]
Description=ONIE boot partition

[Mount]
What=LABEL=ONIE-BOOT
Where=/onieboot
Type=auto
Options=defaults

[Install]
WantedBy=multi-user.target
EOF

cat >/etc/systemd/system/sonic-operator-onie-install.service <<'EOF'
[Unit]
Description=Configure next boot for ONIE install discovery
Requires=onieboot.mount
After=onieboot.mount

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'grub-editenv /host/grub/grubenv set next_entry=ONIE'
ExecStart=/bin/sh -c 'grub-editenv /onieboot/grub/grubenv set onie_mode=install'

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now onieboot.mount
systemctl enable --now sonic-operator-onie-install.service

config hostname 'switch-1.lab.example'
config save -y

# containers
if ! (
install -d -m 0700 /etc/sonic-operator/credentials &&
install -d -m 0700 '/etc/sonic-operator/credentials/wirelet' &&
printf '%s' 'YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCg==' | base64 -d >'/etc/sonic-operator/credentials/wirelet/control-kubeconfig' &&
chown 65532:65532 '/etc/sonic-operator/credentials/wirelet/control-kubeconfig' &&
chmod 0600 '/etc/sonic-operator/credentials/wirelet/control-kubeconfig' &&
docker pull 'ghcr.io/hardikdr/wirelet:fixed-1' &&
(docker rm -f 'wirelet' >/dev/null 2>&1 || true) &&
docker run -d --name 'wirelet' --network host --restart unless-stopped --user '65532:65532' -e KUBECONFIG=/var/run/sonic-operator/control-kubeconfig -v '/etc/sonic-operator/credentials/wirelet/control-kubeconfig:/var/run/sonic-operator/control-kubeconfig:ro' 'ghcr.io/hardikdr/wirelet:fixed-1' '--name=switch-1' '--interface=Ethernet0'
); then
  echo 'sonic-operator: container wirelet failed; continuing' >&2
fi
if ! (
docker pull 'ghcr.io/giluerre/sonic-agent:latest' &&
(docker rm -f 'sonic-agent' >/dev/null 2>&1 || true) &&
docker run -d --name 'sonic-agent' --network host --restart unless-stopped --user '0' -v '/var/run/dbus:/var/run/dbus:rw' -v '/etc/sonic/sonic_version.yml:/etc/sonic/sonic_version.yml:ro' --entrypoint '/switch-agent-server' 'ghcr.io/giluerre/sonic-agent:latest' '-port' '57400'
); then
  echo 'sonic-operator: container sonic-agent failed; continuing' >&2
fi
sync
